 # app/repository/abc.py
from abc import ABC, abstractmethod
from typing import Protocol, List, Optional
from app.domain.models import User, Exercise, Result
from app.config.config import get_settings
settings = get_settings()          # luôn lấy cùng một instance
class IUserRepo(Protocol):
    @abstractmethod
    def get_by_email(self, email: str) -> Optional[User]: ...
    @abstractmethod
    def add(self, user: User) -> User: ...

class IExerciseRepo(Protocol):
    def list_all(self) -> List[Exercise]: ...
    def get(self, exercise_id: int) -> Optional[Exercise]: ...
    def add(self, ex: Exercise) -> Exercise: ...

class IResultRepo(Protocol):
    def add(self, r: Result) -> Result: ...
    def list_by_user(self, user_id: int) -> List[Result]: ...

