from app.repository.sqlite import SessionLocal, ExerciseRepoSQL
from app.domain.models import Exercise

exercises = [
    ("Introduce yourself.", "My name is Anna. I am 20 years old. I live in Ho Chi Minh City."),
    ("Talk about your favorite hobby.", "My favorite hobby is reading books. I read every evening before bed."),
    ("Describe your family.", "I have a small family. There are four people: my parents, my brother and me."),
    ("Talk about your daily routine.", "Every morning, I wake up at 6 a.m., brush my teeth, and have breakfast. Then I go to school."),
    ("What did you do last weekend?", "Last weekend, I visited my grandparents and helped them in the garden."),
    ("Talk about your favorite food.", "My favorite food is pho. It is a traditional Vietnamese noodle soup."),
    ("Describe your best friend.", "My best friend is Minh. He is friendly, funny, and always helps me."),
    ("Where do you want to travel? Why?", "I want to travel to Japan because I love Japanese culture and food."),
    ("What do you do to stay healthy?", "I do exercise every morning and eat a lot of fruits and vegetables."),
    ("Talk about your future plan.", "I plan to become a software engineer and work for a big company."),
    ("What is your favorite subject at school?", "My favorite subject is English because I like learning new languages."),
    ("Describe your hometown.", "My hometown is peaceful. It has many trees and friendly people."),
    ("Talk about a person you admire.", "I admire my mother because she is hardworking and caring."),
    ("What do you like to do in your free time?", "In my free time, I like to listen to music and play badminton."),
    ("Tell me about your dream job.", "My dream job is to be a doctor because I want to help sick people."),
    ("Describe your favorite season.", "My favorite season is summer because I can go swimming and travel."),
    ("How do you go to school or work?", "I go to school by bicycle. It is healthy and good for the environment."),
    ("What is your favorite movie?", "My favorite movie is “Harry Potter” because it is magical and exciting."),
    ("Describe a festival you like.", "I like Tet holiday. My family prepares special food and gives lucky money."),
    ("What is your daily breakfast?", "I usually have bread and milk for breakfast."),
    ("Do you have any pets?", "Yes, I have a cat. It is playful and cute."),
    ("What do you do on Sundays?", "On Sundays, I clean my room and go out with my friends."),
    ("What time do you usually wake up?", "I usually wake up at 6:30 a.m. every day."),
    ("Describe your favorite place in your city.", "My favorite place is the city park. It is green and quiet."),
    ("How do you relax after studying or working?", "I watch movies or listen to soft music to relax."),
    ("What is your favorite book?", "My favorite book is “The Little Prince” because it is meaningful."),
    ("What do you do to protect the environment?", "I save electricity, use less plastic, and plant trees."),
    ("Who is your best teacher?", "My best teacher is Ms. Lan. She is kind and explains everything clearly."),
    ("Describe a memorable trip you had.", "Last year, I went to Da Nang with my family. We visited the beach and enjoyed local food."),
    ("What is your favorite sport?", "My favorite sport is football. I often play with my friends after school."),
    ("How do you keep in touch with your friends?", "I keep in touch by calling, texting, or using social media."),
    ("Tell me about your favorite music.", "I like pop music because it is energetic and catchy."),
    ("What do you do when you feel stressed?", "When I feel stressed, I take a walk or talk to my best friend."),
    ("What’s your plan for this weekend?", "This weekend, I plan to visit my grandparents and study for my exams."),
    ("Describe a technology you use every day.", "I use my smartphone every day for learning and connecting with friends."),
    ("Do you prefer studying alone or in a group?", "I prefer studying in a group because I can share ideas."),
    ("What foreign language would you like to learn?", "I would like to learn Japanese because I love Japanese culture."),
    ("Talk about a time you helped someone.", "I helped my classmate with her homework when she was sick."),
    ("What is your favorite drink?", "My favorite drink is orange juice. It is fresh and healthy."),
    ("What do you usually do before going to bed?", "Before bed, I read a book and prepare things for the next day."),
    ("What is your favorite color?", "My favorite color is blue because it is calm and peaceful."),
    ("Describe your house.", "My house is small but cozy. It has two bedrooms and a garden."),
    ("How many languages can you speak?", "I can speak Vietnamese and a little English."),
    ("What do you usually do after dinner?", "After dinner, I help my parents wash the dishes and then do my homework."),
    ("Describe a family member you love.", "I love my younger sister. She is funny and always makes me laugh."),
    ("What do you do when it rains?", "When it rains, I stay indoors and read books or watch TV."),
    ("What are you afraid of?", "I am afraid of snakes because they look scary."),
    ("How do you celebrate your birthday?", "I celebrate my birthday with my family and close friends. We eat cake and play games."),
    ("What is your favorite animal?", "My favorite animal is the dog because it is loyal and friendly."),
    ("What kind of weather do you like?", "I like cool and sunny weather because I can go outside and play."),
    ("Describe your best childhood memory.", "My best memory is playing hide and seek with my cousins during the summer holiday."),
    ("What do you want to be in the future?", "I want to be a teacher because I enjoy helping others learn."),
    ("What is your favorite fruit?", "My favorite fruit is mango. It is sweet and juicy."),
    ("How often do you exercise?", "I exercise three times a week to stay healthy."),
    ("What would you do if you won a lot of money?", "If I won a lot of money, I would travel around the world and help my parents."),
    ("What do you usually wear on weekends?", "On weekends, I usually wear a T-shirt and jeans because they are comfortable."),
    ("What is the most important thing in your life?", "The most important thing is my family because they always support me."),
    ("Describe a festival in your country.", "Mid-Autumn Festival is a special event in Vietnam. Children carry lanterns and eat mooncakes."),
    ("What is your favorite dessert?", "My favorite dessert is ice cream, especially chocolate flavor."),
    ("Who is your role model?", "My father is my role model. He is hardworking and wise."),
    ("What is your favorite app or website?", "My favorite app is YouTube because I can learn many things and watch fun videos."),
    ("How do you spend your summer holiday?", "I visit my grandparents and play with my cousins during summer."),
    ("Do you like to cook? Why or why not?", "Yes, I like to cook because I can make delicious food for my family."),
    ("What is your favorite holiday destination?", "My favorite destination is Da Lat because it is cool and beautiful."),
    ("What time do you usually go to bed?", "I usually go to bed at 10 p.m."),
    ("How do you help your parents at home?", "I help my parents by cleaning my room and doing the dishes."),
    ("What do you like to do on rainy days?", "On rainy days, I like to draw and listen to music."),
    ("What is your favorite school activity?", "My favorite school activity is playing sports during break time."),
    ("Do you prefer cats or dogs?", "I prefer dogs because they are loyal and love to play."),
    ("What is something you are good at?", "I am good at painting and singing."),
    ("Describe your favorite teacher.", "My favorite teacher is Mr. Nam. He teaches math and makes the lessons interesting."),
    ("What do you want to improve about yourself?", "I want to improve my English speaking skills."),
    ("How do you prepare for exams?", "I review my notes, practice old tests, and ask my friends for help."),
    ("What is your favorite family tradition?", "Every Sunday, my family has dinner together and talks about our week."),
    ("What country would you like to visit?", "I would like to visit France because I love French food and culture."),
    ("How do you make new friends?", "I smile, introduce myself, and talk about our common interests."),
    ("What do you do to keep fit?", "I play sports and eat healthy food."),
    ("What is your favorite way to relax?", "I like to read books or listen to soft music to relax."),
    ("What is your favorite snack?", "My favorite snack is potato chips."),
    ("What is a place you want to live in the future?", "I want to live in a big city with many job opportunities."),
    ("What is your dream house like?", "My dream house is modern with a big garden and a swimming pool."),
    ("What do you do if you get lost in a new place?", "I ask someone for help or use my phone to find the way."),
    ("What is your favorite thing to do with your friends?", "I like to go to the movies or have a picnic with my friends."),
    ("How often do you go shopping?", "I go shopping once a week with my mother."),
    ("What do you think is important for a good life?", "Good health, loving family, and a positive attitude are important."),
    ("Do you enjoy helping others?", "Yes, I feel happy when I can help other people."),
    ("What makes you laugh?", "Funny jokes and my friends’ stories make me laugh."),
    ("What would you do if you could change the world?", "I would stop pollution and make sure everyone has enough food."),
    ("What is your favorite thing about your school?", "My favorite thing is the school library. It has many interesting books."),
    ("What do you want to learn this year?", "I want to learn how to play the guitar and improve my English.")
]  # <- Đóng list ở đây!

db = SessionLocal()
for prompt, answer in exercises:
    ex = Exercise(prompt=prompt, answer=answer, created_by=1)
    ExerciseRepoSQL(db).add(ex)
db.close()
print("Đã thêm bài tập mẫu thành công.")
